"use client";
import {useEffect,useState} from "react";
import {SummaryCards} from "@/components/academy/analytics/SummaryCards";
import {RetentionChart} from "@/components/academy/analytics/RetentionChart";
import {Filters} from "@/components/academy/analytics/Filters";
import {CampaignTable} from "@/components/academy/analytics/CampaignTable";
type Data={metrics:Record<string,number>;retention:{second:number;endSecond:number;percent:number}[]};
const iso=(d:Date)=>d.toISOString().slice(0,10);
export default function Analytics(){const now=new Date();const [range,setRange]=useState('7'),[from,setFrom]=useState(iso(new Date(now.getTime()-7*864e5))),[to,setTo]=useState(iso(now)),[source,setSource]=useState(''),[campaign,setCampaign]=useState(''),[adset,setAdset]=useState(''),[ad,setAd]=useState(''),[data,setData]=useState<Data|null>(null),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true);function query(){const p=new URLSearchParams({from:`${from}T03:00:00.000Z`,to:`${to}T26:59:59.999Z`});if(source)p.set('source',source);if(campaign)p.set('utmCampaign',campaign);if(adset)p.set('adsetId',adset);if(ad)p.set('adId',ad);setLoading(true);Promise.all([fetch('/api/admin/academy/summary?'+p).then(r=>r.json()),fetch('/api/admin/academy/breakdown?'+p).then(r=>r.json())]).then(([a,b])=>{setData(a);setRows(b.rows||[])}).finally(()=>setLoading(false))}useEffect(query,[]);function choose(v:string){setRange(v);const d=new Date();if(v==='today'){setFrom(iso(d));setTo(iso(d))}if(v==='7'){setFrom(iso(new Date(d.getTime()-7*864e5)));setTo(iso(d))}if(v==='30'){setFrom(iso(new Date(d.getTime()-30*864e5)));setTo(iso(d))}}return <main className="mx-auto max-w-7xl space-y-5 p-6"><div><p className="text-sm text-orange-400">Central Operacional · Academy</p><h1 className="text-3xl font-bold">Analytics da VSL</h1><p className="text-sm text-slate-400">{from} até {to} · funil corretor-academy · pitch oficial 33:54 (2034s)</p></div><Filters range={range} setRange={choose} from={from} to={to} setFrom={setFrom} setTo={setTo} source={source} setSource={setSource} campaign={campaign} setCampaign={setCampaign} adset={adset} setAdset={setAdset} ad={ad} setAd={setAd} apply={query}/>{loading?<div className="py-20 text-center text-slate-400">Carregando dados reais…</div>:data&&<><SummaryCards metrics={data.metrics}/><RetentionChart data={data.retention}/><CampaignTable rows={rows} onSelect={name=>{setCampaign(name);query()}}/></>}</main>}
