"use client";
import Link from "next/link";
import DocumentsPanel from "./DocumentsPanel";
import WorkflowPanel from "./WorkflowPanel";
import CorrespondentMessage from "./CorrespondentMessage";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useSearchParams } from "next/navigation";

export const statuses = ["EM_MONTAGEM", "AGUARDANDO_DOCUMENTOS", "PRONTA_PARA_ANALISE", "AGUARDANDO_CORRESPONDENTE", "PENDENCIA_DOCUMENTAL", "EM_REANALISE", "EM_ANALISE", "APROVADO", "CONDICIONADO", "REPROVADO"];
const relationships = ["TITULAR", "CONJUGE", "DEVEDOR_SOLIDARIO", "FIADOR", "FILHO", "PARENTE", "PROCURADOR", "TERCEIRO", "OUTRO"];
export const label = (value: string) => value.toLowerCase().replaceAll("_", " ");
const control = "w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm";
const button = "rounded-lg border px-3 py-2 text-sm hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50";
const panel = "rounded-xl border bg-white p-4 sm:p-6";
export async function api<T>(url: string, method = "GET", body?: unknown): Promise<T> {
  const response = await fetch(url, { method, cache: "no-store", headers: body === undefined ? undefined : { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error ?? "Não foi possível concluir a operação.");
  return data;
}
function Message({ value }: { value: string }) { return value ? <p role="status" className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm">{value}</p> : null; }
function Field({ name, title, required, value = "", type = "text" }: { name: string; title: string; required?: boolean; value?: string; type?: string }) {
  return <label className="block space-y-1 text-sm"><span>{title}{required ? " *" : ""}</span><input className={control} name={name} type={type} required={required} defaultValue={value} maxLength={name === "cpf" ? 18 : 320} /></label>;
}
type Option = { id: string; name: string; phone?: string | null; email?: string | null };
function Picker({ kind, name, title, required, initial, builderId, onSelect }: { kind: string; name: string; title: string; required?: boolean; initial?: Option; builderId?: string; onSelect?: (option?: Option) => void }) {
  const [q, setQ] = useState(""); const [items, setItems] = useState<Option[]>([]); const [error, setError] = useState(""); const [selected, setSelected] = useState(initial?.id ?? "");
  useEffect(() => {
    let live = true;
    const timer = setTimeout(() => { api<{ items: Option[] }>(`/api/documentacoes/opcoes?${new URLSearchParams({ kind, q, ...(builderId ? { builderId } : {}) })}`).then(data => { if (live) { setItems(data.items); setError(""); } }).catch(e => { if (live) setError(e.message); }); }, 250);
    return () => { live = false; clearTimeout(timer); };
  }, [q, kind, builderId]);
  const options = initial && !items.some(row => row.id === initial.id) ? [initial, ...items] : items;
  return <label className="block space-y-1 text-sm"><span>{title}{required ? " *" : ""}</span><input className={control} aria-label={`Buscar ${title}`} placeholder="Buscar pelo nome (até 30 resultados)" value={q} onChange={e => setQ(e.target.value)} /><select className={control} name={name} required={required} value={selected} onChange={e => { setSelected(e.target.value); onSelect?.(options.find(row => row.id === e.target.value)); }}><option value="">Selecione</option>{options.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select>{error && <span role="status" className="text-red-700">{error}</span>}</label>;
}
function Pager({ page, total, change }: { page: number; total: number; change: (page: number) => void }) {
  return <div className="flex flex-wrap items-center gap-3 text-sm"><button className={button} disabled={page <= 1} onClick={() => change(page - 1)}>Anterior</button><span>Página {page} · {total} registros</span><button className={button} disabled={page * 20 >= total} onClick={() => change(page + 1)}>Próxima</button></div>;
}
type FolderRow = { id: string; status: string; version: number; createdAt: string; updatedAt: string; people: { name: string; cpf: string | null }[]; broker: Option; correspondent: Option | null };
type FolderList = { items: FolderRow[]; total: number; page: number; groups: { status: string; _count: { _all: number } }[] };
export function FolderListView({ overview = false }: { overview?: boolean }) {
  const searchParams = useSearchParams();
  const [data, setData] = useState<FolderList>(); const [message, setMessage] = useState(""); const [params, setParams] = useState(() => {
    const result = new URLSearchParams(searchParams.toString());
    if (overview && !result.has("from")) { const today = new Intl.DateTimeFormat("en-CA", { timeZone: "America/Sao_Paulo", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); result.set("from", `${today.slice(0, 7)}-01`); result.set("to", today); }
    return result.toString();
  });
  useEffect(() => { let live = true; api<FolderList>(`/api/documentacoes/pastas?${params}`).then(result => { if (live) { setData(result); setMessage(""); } }).catch(e => { if (live) { setData(undefined); setMessage(e.message); } }); return () => { live = false; }; }, [params]);
  function filter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setData(undefined); const fields = new FormData(event.currentTarget); const query = new URLSearchParams(); fields.forEach((value, key) => { if (String(value)) query.set(key, String(value)); }); setParams(query.toString()); }
  function page(value: number) { const query = new URLSearchParams(params); query.set("page", String(value)); setData(undefined); setParams(query.toString()); }
  function period(offset: number) {
    const parts = new Intl.DateTimeFormat("en", { timeZone: "America/Sao_Paulo", year: "numeric", month: "2-digit" }).formatToParts(new Date());
    const year = Number(parts.find(part => part.type === "year")!.value); const month = Number(parts.find(part => part.type === "month")!.value) - 1 + offset;
    const query = new URLSearchParams(params); query.delete("page"); query.set("from", new Date(Date.UTC(year, month, 1)).toISOString().slice(0, 10)); query.set("to", new Date(Date.UTC(year, month + 1, 0)).toISOString().slice(0, 10)); setData(undefined); setParams(query.toString());
  }
  const query = new URLSearchParams(params);
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-xl font-semibold">{overview ? "Visão geral de Documentações" : "Pastas"}</h1><Link className={button} href="/admin/documentacoes/pastas/nova">Nova pasta</Link></div><Message value={message} />
    {overview && <div className="flex flex-wrap gap-2"><button className={button} onClick={() => period(0)}>Este mês</button><button className={button} onClick={() => period(-1)}>Mês anterior</button><span className="self-center text-sm">Ou escolha um período personalizado abaixo.</span></div>}<form key={params} className={`${panel} grid gap-3 sm:grid-cols-2 lg:grid-cols-3`} onSubmit={filter}>
      <Field name="q" title="Nome ou CPF" value={query.get("q") ?? ""} /><label className="space-y-1 text-sm">Status<select name="status" className={control} defaultValue={query.get("status") ?? ""}><option value="">Todos</option>{statuses.map(status => <option key={status} value={status}>{label(status)}</option>)}</select></label>
      <Field name="from" title="Criadas de" type="date" value={query.get("from") ?? ""} /><Field name="to" title="Até" type="date" value={query.get("to") ?? ""} />
      <Picker kind="broker" name="brokerId" title="Corretor" initial={query.get("brokerId") ? { id: query.get("brokerId")!, name: "Corretor selecionado" } : undefined} /><Picker kind="correspondent" name="correspondentId" title="Correspondente" initial={query.get("correspondentId") ? { id: query.get("correspondentId")!, name: "Correspondente selecionado" } : undefined} />
      <button className={button} type="submit">Aplicar filtros</button>
    </form>
    {overview && data && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className={panel}><p className="text-sm">Total no período filtrado</p><strong className="text-2xl">{data.total}</strong></div>{statuses.map(status => <div key={status} className={panel}><p className="text-sm capitalize">{label(status)}</p><strong className="text-2xl">{data.groups.find(row => row.status === status)?._count._all ?? 0}</strong></div>)}</div>}
    {data ? <><h2 className="font-semibold">{overview ? "Pastas recentes no período" : "Resultados"}</h2><div className={`${panel} overflow-x-auto`}><table className="w-full min-w-[650px] text-left text-sm"><thead><tr>{["Titular", "CPF", "Corretor", "Correspondente", "Status", "Criada", "Atualizada", ""].map(title => <th key={title} className="p-2">{title}</th>)}</tr></thead><tbody>{data.items.map(row => <tr key={row.id} className="border-t"><td className="p-2">{row.people[0]?.name ?? "Titular ausente"}</td><td className="p-2">{row.people[0]?.cpf ?? "—"}</td><td className="p-2">{row.broker.name}</td><td className="p-2">{row.correspondent?.name ?? "Não atribuído"}</td><td className="p-2 capitalize">{label(row.status)}</td><td className="p-2">{new Date(row.createdAt).toLocaleDateString("pt-BR", { timeZone: "America/Sao_Paulo" })}</td><td className="p-2">{new Date(row.updatedAt).toLocaleDateString("pt-BR", { timeZone: "America/Sao_Paulo" })}</td><td className="p-2"><Link className="underline" href={`/admin/documentacoes/pastas/${row.id}`}>Abrir</Link></td></tr>)}</tbody></table>{!data.total && <p className="p-4">Nenhuma pasta encontrada para os filtros.</p>}</div><Pager page={data.page} total={data.total} change={page} /></> : !message && <p role="status">Carregando pastas…</p>}
  </div>;
}
type Person = { id: string; name: string; cpf: string | null; phone: string | null; email: string | null; birthDate: string | null; relationship: string };
type Folder = Omit<FolderRow, "people"> & { administrativeObservation: string | null; people: Person[]; crmLeadId: string | null; construtora: { id: string; name: string } | null; empreendimento: { id: string; name: string } | null };
function personFields(data: FormData) { return Object.fromEntries(["name", "cpf", "phone", "email", "birthDate", "relationship"].map(key => [key, String(data.get(key) ?? "")])); }
function PersonFields({ person, titular = false }: { person?: Person; titular?: boolean }) {
  return <><Field name="name" title="Nome" required value={person?.name} /><Field name="cpf" title="CPF" required={titular} value={person?.cpf ?? ""} /><Field name="phone" title="Telefone" required={titular} value={person?.phone ?? ""} /><Field name="email" title="E-mail" type="email" value={person?.email ?? ""} /><Field name="birthDate" title="Nascimento" type="date" value={person?.birthDate?.slice(0, 10) ?? ""} /><label className="text-sm">Vínculo<select className={control} name="relationship" defaultValue={titular ? "TITULAR" : person?.relationship ?? "OUTRO"}>{(titular ? ["TITULAR"] : relationships.filter(row => row !== "TITULAR")).map(row => <option key={row} value={row}>{label(row)}</option>)}</select></label></>;
}
export function FolderForm({ folder, saved }: { folder?: Folder; saved?: () => void }) {
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [builder, setBuilder] = useState(folder?.construtora?.id ?? ""); const [crm, setCrm] = useState<Option>();
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setMessage("");
    const body = { ...Object.fromEntries(form), holder: personFields(form), ...(folder ? { version: folder.version } : {}) };
    try { const result = await api<{ id: string }>(folder ? `/api/documentacoes/pastas/${folder.id}` : "/api/documentacoes/pastas", folder ? "PATCH" : "POST", body); if (saved) saved(); else window.location.assign(`/admin/documentacoes/pastas/${result.id}`); } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); }
  }
  const holder = folder?.people.find(person => person.relationship === "TITULAR");
  return <form className={`${panel} space-y-4`} onSubmit={submit}><Message value={message} /><p className="text-sm text-gray-600">Campos com * são obrigatórios. A pasta pode ser criada sem cliente CRM.</p>
    <div className="grid gap-4 sm:grid-cols-2"><Picker kind="crm" name="crmLeadId" title="Cliente CRM (opcional)" initial={folder?.crmLeadId ? { id: folder.crmLeadId, name: "Cliente vinculado" } : undefined} onSelect={setCrm} /><Picker kind="broker" name="brokerId" title="Corretor responsável" required initial={folder?.broker} /><Picker kind="correspondent" name="correspondentId" title="Correspondente" initial={folder?.correspondent ?? undefined} /><Picker kind="builder" name="construtoraId" title="Construtora" initial={folder?.construtora ? { id: folder.construtora.id, name: folder.construtora.name } : undefined} onSelect={row => setBuilder(row?.id ?? "")} /><Picker key={builder} kind="property" name="empreendimentoId" title="Empreendimento" builderId={builder} initial={folder?.empreendimento && builder === folder.construtora?.id ? { id: folder.empreendimento.id, name: folder.empreendimento.name } : undefined} />
      {folder && <label className="text-sm">Status<select name="status" className={control} defaultValue={folder.status}>{(folder.status === "PENDENCIA_DOCUMENTAL" ? [folder.status] : statuses.slice(0, 2)).map(row => <option key={row} value={row}>{label(row)}</option>)}</select></label>}
    </div><h2 className="font-semibold">Titular</h2><div key={crm?.id ?? "manual"} className="grid gap-4 sm:grid-cols-2"><PersonFields titular person={holder ?? (crm ? { id: "", name: crm.name, cpf: null, phone: crm.phone ?? null, email: crm.email ?? null, birthDate: null, relationship: "TITULAR" } : undefined)} /></div>
    <label className="block text-sm">Observação administrativa<textarea className={control} name="administrativeObservation" maxLength={3000} defaultValue={folder?.administrativeObservation ?? ""} /></label><button className={button} disabled={busy}>{busy ? "Salvando…" : "Salvar pasta"}</button>
  </form>;
}
type DocumentType = { id: string; code: string; name: string; description: string | null; defaultRequired: boolean; sortOrder: number; isActive: boolean; updatedAt: string };
type Detail = { documentCount: number; folder: Folder & { correspondent: { id: string; name: string; email: string; isActive: boolean; updatedAt: string } | null }; types: DocumentType[]; events: { id: string; eventType: string; createdAt: string; actor: { name: string } | null }[]; eventCount: number; page: number };
const eventLabels: Record<string, string> = { DOCUMENT_REVIEW_SUBMITTED: "Enviada para análise", DOCUMENT_REVIEW_RESUBMITTED: "Reenviada para análise", DOCUMENT_REVIEW_STARTED: "Análise iniciada", DOCUMENT_ISSUE_CREATED: "Pendência criada", DOCUMENT_ISSUE_UPDATED: "Pendência revisada", DOCUMENT_ISSUE_CANCELLED: "Pendência cancelada", DOCUMENT_ISSUE_RESOLVED: "Pendência resolvida", DOCUMENT_REVIEW_NOTE_SAVED: "Parecer salvo", DOCUMENT_REVIEW_APPROVED: "Pasta aprovada", DOCUMENT_REVIEW_CONDITIONED: "Aprovação condicionada", DOCUMENT_REVIEW_REJECTED: "Pasta reprovada", DOCUMENT_REVIEW_CHANGES_REQUESTED: "Correções solicitadas", FOLDER_CREATED: "Pasta criada", FOLDER_UPDATED: "Pasta atualizada", BROKER_ASSIGNED: "Corretor atribuído", CORRESPONDENT_ASSIGNED: "Correspondente atribuído", CORRESPONDENT_CHANGED: "Correspondente alterado", PERSON_ADDED: "Pessoa adicionada", PERSON_UPDATED: "Pessoa atualizada", PERSON_REMOVED: "Pessoa removida", DOCUMENT_UPLOAD_STARTED: "Upload iniciado", DOCUMENT_ADDED: "Documento adicionado", DOCUMENT_INVALIDATED: "Documento invalidado", DOCUMENT_REPLACED: "Documento substituído" };
export function FolderDetailView({ id, owner = false }: { id: string; owner?: boolean }) {
  const [data, setData] = useState<Detail>(); const [message, setMessage] = useState(""); const [tab, setTab] = useState("Resumo"); const [page, setPage] = useState(1); const [revision, setRevision] = useState(0); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState<Person | null>(null);
  const refresh = useCallback(() => { setEditing(null); setRevision(value => value + 1); }, []);
  useEffect(() => { let live = true; api<Detail>(`/api/documentacoes/pastas/${id}?page=${page}`).then(result => { if (live) { setData(result); setMessage(""); } }).catch(e => { if (live) { setData(undefined); setMessage(e.message); } }); return () => { live = false; }; }, [id, page, revision]);
  async function personChange(method: string, personId: string | null, values: unknown) {
    setBusy(true); setMessage("");
    try { await api(`/api/documentacoes/pastas/${id}/pessoas${personId ? `/${personId}` : ""}`, method, { ...(values as object), version: data!.folder.version }); refresh(); } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); }
  }
  const editable = !!data && ["EM_MONTAGEM", "AGUARDANDO_DOCUMENTOS", "PENDENCIA_DOCUMENTAL"].includes(data.folder.status);
  return <div className="space-y-4"><Link className="text-sm underline" href="/admin/documentacoes/pastas">Voltar às pastas</Link><Message value={message} />{data ? <><h1 className="text-xl font-semibold">{data.folder.people.find(row => row.relationship === "TITULAR")?.name ?? "Pasta"}</h1><div className="rounded-xl border bg-white p-4 text-sm"><span className="rounded-full border bg-gray-50 px-3 py-1 capitalize">{label(data.folder.status)}</span><p className="mt-3">CPF: {data.folder.people.find(row => row.relationship === "TITULAR")?.cpf ?? "—"} · Corretor: {data.folder.broker.name} · Correspondente: {data.folder.correspondent?.name ?? "Não atribuído"}</p><p>Criada: {new Date(data.folder.createdAt).toLocaleString("pt-BR")} · Atualizada: {new Date(data.folder.updatedAt).toLocaleString("pt-BR")} · Versão {data.folder.version}</p><button className={`${button} mt-3`} onClick={refresh}>Recarregar pasta</button></div><div className="flex flex-wrap gap-2" role="tablist">{["Resumo", "Pessoas", "Documentos", "Análise", "Histórico"].map(row => <button key={row} className={`${button} ${tab === row ? "bg-gray-100 font-semibold" : ""}`} role="tab" aria-selected={tab === row} onClick={() => setTab(row)}>{row}</button>)}</div>
    {data.folder.correspondent && <CorrespondentMessage correspondent={data.folder.correspondent} clientName={data.folder.people.find(row => row.relationship === "TITULAR")?.name ?? "Cliente"} documentCount={data.documentCount} status={data.folder.status} owner={owner} onChange={refresh} />}
    {tab === "Resumo" && (editable ? <FolderForm key={data.folder.version} folder={data.folder} saved={refresh} /> : <div className={panel}><p>Corretor: {data.folder.broker.name}</p><p>Correspondente: {data.folder.correspondent?.name ?? "Não atribuído"}</p><p>Construtora: {data.folder.construtora?.name ?? "—"}</p><p>Empreendimento: {data.folder.empreendimento?.name ?? "—"}</p><p>Observação: {data.folder.administrativeObservation ?? "—"}</p><p className="mt-3">Edição indisponível neste status.</p></div>)}
    {tab === "Pessoas" && <div className="space-y-4"><div className={panel}>{data.folder.people.map(person => <div key={person.id} className="flex flex-wrap items-center justify-between gap-3 border-b py-3"><div><strong>{person.name}</strong><p className="text-sm capitalize">{label(person.relationship)} · {person.cpf ?? "Sem CPF"} · {person.phone ?? "Sem telefone"} · {person.email ?? "Sem e-mail"}</p></div><div className="flex gap-2"><button className={button} disabled={!editable || busy} onClick={() => setEditing(person)}>Editar</button>{person.relationship !== "TITULAR" && <button className={button} disabled={!editable || busy} onClick={() => { if (window.confirm("Remover esta pessoa da pasta?")) void personChange("DELETE", person.id, {}); }}>Remover</button>}</div></div>)}</div>{editable && <form key={editing?.id ?? `new-${revision}`} className={`${panel} space-y-4`} onSubmit={event => { event.preventDefault(); void personChange(editing ? "PATCH" : "POST", editing?.id ?? null, personFields(new FormData(event.currentTarget))); }}><h2 className="font-semibold">{editing ? "Editar pessoa" : "Adicionar pessoa"}</h2><div className="grid gap-3 sm:grid-cols-2"><PersonFields person={editing ?? undefined} titular={editing?.relationship === "TITULAR"} /></div><div className="flex gap-2"><button className={button} disabled={busy}>Salvar pessoa</button>{editing && <button type="button" className={button} onClick={() => setEditing(null)}>Cancelar edição</button>}</div></form>}</div>}
    {tab === "Documentos" && <DocumentsPanel folderId={id} admin onChange={refresh} />}
    {tab === "Análise" && <WorkflowPanel folderId={id} onChange={refresh} />}
    {tab === "Histórico" && <div className={`${panel} space-y-3`}>{data.events.map(event => <div key={event.id} className="border-b pb-3 text-sm"><strong>{eventLabels[event.eventType] ?? label(event.eventType)}</strong><p>{event.actor?.name ?? "Sistema"} · {new Date(event.createdAt).toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo" })}</p></div>)}<Pager page={data.page} total={data.eventCount} change={setPage} /></div>}
  </> : !message && <p role="status">Carregando pasta…</p>}</div>;
}
type Correspondent = { id: string; name: string; email: string; isActive: boolean; createdAt: string; updatedAt: string; _count: { documentationCorrespondentFolders: number } };
export function CorrespondentsView({ owner }: { owner: boolean }) {
  const [data, setData] = useState<{ items: Correspondent[]; total: number; page: number }>(); const [params, setParams] = useState(""); const [revision, setRevision] = useState(0); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { let live = true; api<typeof data>(`/api/documentacoes/correspondentes?${params}`).then(result => { if (live) setData(result); }).catch(e => { if (live) setMessage(e.message); }); return () => { live = false; }; }, [params, revision]);
  async function action(url: string, method: string, body: unknown, success: string) { setBusy(true); setMessage(""); try { await api(url, method, body); setMessage(success); setRevision(value => value + 1); return true; } catch (e) { setMessage((e as Error).message); return false; } finally { setBusy(false); } }
  return <div className="space-y-4"><h1 className="text-xl font-semibold">Correspondentes</h1><Message value={message} /><form className={`${panel} flex flex-wrap gap-3`} onSubmit={event => { event.preventDefault(); setParams(new URLSearchParams(Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>).toString()); }}><Field name="q" title="Nome" /><label className="text-sm">Situação<select className={control} name="active"><option value="">Todos</option><option value="true">Ativos</option><option value="false">Inativos</option></select></label><button className={button}>Filtrar</button></form>
    {data && <><div className={panel}>{data.items.map(row => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 border-b py-4"><div><strong>{row.name}</strong><p className="text-sm">{row.email} · {row.isActive ? "Ativo" : "Inativo"} · Criado em {new Date(row.createdAt).toLocaleDateString("pt-BR")}</p><Link className="text-sm underline" href={`/admin/documentacoes/pastas?correspondentId=${row.id}`}>{row._count.documentationCorrespondentFolders} pastas atribuídas</Link></div>{owner && <div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={() => void action(`/api/documentacoes/correspondentes/${row.id}`, "PATCH", { isActive: !row.isActive, updatedAt: row.updatedAt }, "Situação atualizada.")}>{row.isActive ? "Inativar" : "Ativar"}</button><button className={button} disabled={busy || !row.isActive} onClick={() => void action(`/api/documentacoes/correspondentes/${row.id}/recuperar-acesso`, "POST", {}, "Solicitação de recuperação enviada por e-mail.")}>Recuperar acesso</button></div>}</div>)}{!data.total && <p>Nenhum correspondente encontrado.</p>}</div><Pager page={data.page} total={data.total} change={page => { const query = new URLSearchParams(params); query.set("page", String(page)); setParams(query.toString()); }} /></>}
    {owner && <div className="grid gap-4 lg:grid-cols-2"><form className={`${panel} space-y-3`} onSubmit={event => { event.preventDefault(); const form = event.currentTarget; void action("/api/documentacoes/correspondentes", "POST", Object.fromEntries(new FormData(form)), "Correspondente criado.").then(ok => { if (ok) form.reset(); }); }}><h2 className="font-semibold">Criar correspondente</h2><Field name="name" title="Nome" required /><Field name="email" title="E-mail" type="email" required /><Field name="password" title="Senha inicial (mínimo 8 caracteres)" type="password" required /><Field name="confirmPassword" title="Confirmar senha" type="password" required /><button className={button} disabled={busy}>Criar</button></form><form className={`${panel} space-y-3`} onSubmit={event => { event.preventDefault(); void action("/api/documentacoes/correspondentes/convite", "POST", Object.fromEntries(new FormData(event.currentTarget)), "Convite enviado por e-mail."); }}><h2 className="font-semibold">Convidar correspondente</h2><Field name="email" title="E-mail" type="email" required /><p className="text-sm text-gray-600">O convite usa o fluxo existente e fixa o perfil Correspondente Bancário.</p><button className={button} disabled={busy}>Enviar convite</button></form></div>}
  </div>;
}
export function TypesView({ owner }: { owner: boolean }) {
  const [types, setTypes] = useState<DocumentType[]>([]); const [revision, setRevision] = useState(0); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { let live = true; api<{ items: DocumentType[] }>("/api/documentacoes/tipos").then(data => { if (live) setTypes(data.items); }).catch(e => { if (live) setMessage(e.message); }); return () => { live = false; }; }, [revision]);
  async function save(url: string, method: string, body: unknown) { setBusy(true); setMessage(""); try { await api(url, method, body); setRevision(value => value + 1); setMessage("Catálogo atualizado."); } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); } }
  function values(form: HTMLFormElement) { const data = new FormData(form); return { ...Object.fromEntries(data), sortOrder: Number(data.get("sortOrder")), isActive: data.has("isActive"), defaultRequired: data.has("defaultRequired") }; }
  function fields(type?: DocumentType) { return <><Field name="name" title="Nome" required value={type?.name} /><Field name="description" title="Descrição" value={type?.description ?? ""} /><Field name="sortOrder" title="Ordem" type="number" required value={String(type?.sortOrder ?? 0)} /><label className="text-sm"><input name="isActive" type="checkbox" defaultChecked={type?.isActive ?? true} /> Ativo</label><label className="text-sm"><input name="defaultRequired" type="checkbox" defaultChecked={type?.defaultRequired ?? false} /> Obrigatório por padrão</label></>; }
  return <div className="space-y-4"><h1 className="text-xl font-semibold">Configurações documentais</h1><Message value={message} /><p className="text-sm">Tipos são desativados, preservando referências e histórico. Inicializar insere os códigos ausentes sem substituir configurações.</p>{owner && <button className={button} disabled={busy} onClick={() => void save("/api/documentacoes/tipos/inicializar", "POST", {})}>Inicializar os 20 tipos padrão</button>}{types.map(type => <form key={`${type.id}-${type.updatedAt}`} className={`${panel} grid items-end gap-3 sm:grid-cols-2 lg:grid-cols-3`} onSubmit={event => { event.preventDefault(); void save(`/api/documentacoes/tipos/${type.id}`, "PATCH", { ...values(event.currentTarget), updatedAt: type.updatedAt }); }}><p className="text-sm font-semibold">{type.code}</p>{fields(type)}{owner && <button className={button} disabled={busy}>Salvar tipo</button>}</form>)}{owner && <form className={`${panel} grid gap-3 sm:grid-cols-2`} onSubmit={event => { event.preventDefault(); void save("/api/documentacoes/tipos", "POST", values(event.currentTarget)); }}><h2 className="font-semibold sm:col-span-2">Novo tipo documental</h2><Field name="code" title="Código único (MAIÚSCULAS_COM_SUBLINHADO)" required />{fields()}<button className={button} disabled={busy}>Criar tipo</button></form>}</div>;
}
