"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { correspondentStatus, documentationEventLabels } from "@/lib/documentacoes/correspondent-presentation";
import type { workflowView, WorkflowAction } from "@/lib/documentacoes/workflow.server";
type Data = Awaited<ReturnType<typeof workflowView>>;
const box = "rounded-xl border bg-white p-4 space-y-3";
const control = "w-full rounded border p-2 text-sm";
const button = "rounded border px-3 py-2 text-sm disabled:opacity-50";
const label = (value: string) => ({ AGUARDANDO_CORRESPONDENTE: "Aguardando primeira análise", EM_REANALISE: "Aguardando reanálise", EM_ANALISE: "Em análise", PENDENCIA_DOCUMENTAL: "Pendências" }[value] ?? value.toLowerCase().replaceAll("_", " "));
const date = (value: Date | string | null | undefined) => value ? new Date(String(value)).toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo" }) : "—";
export default function WorkflowPanel({ folderId, onChange, correspondent = false, view = "work", correction, revision = 0 }: { folderId: string; onChange?: () => void; correspondent?: boolean; revision?: number; view?: "work" | "history"; correction?: { id: string; personId: string | null; documentTypeId: string | null } }) {
  const [data, setData] = useState<Data>(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [page, setPage] = useState(1); const [issuePage, setIssuePage] = useState(1); const [roundId, setRoundId] = useState("");
  const [observation, setObservation] = useState(""); const draftRound = useRef<string | undefined>(undefined);
  const [editing, setEditing] = useState<Data["issues"][number] | null>(null);
  const [formRevision, setFormRevision] = useState(0);
  const base = `/api/documentacoes/pastas/${folderId}/workflow`;
  const load = useCallback(async () => {
    const response = await fetch(`${base}?page=${page}&issuePage=${issuePage}&roundId=${roundId}`, { cache: "no-store" }); const value = await response.json();
    if (!response.ok) throw new Error(value.error ?? "Não foi possível carregar o workflow.");
    const next = value as Data; setData(next);
    if (draftRound.current !== next.latest?.id) { draftRound.current = next.latest?.id; setObservation(next.note); }
  }, [base, page, issuePage, roundId]);
  useEffect(() => { const timer = setTimeout(() => { void load().catch(error => setMessage(error.message)); }, 0); return () => clearTimeout(timer); }, [load, revision]);
  async function mutate(action: WorkflowAction, values: Record<string, unknown> = {}) {
    if (!data) return; setBusy(true); setMessage("");
    try {
      const response = await fetch(base, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, version: data.folder.version, roundId: data.latest?.id, ...values }) });
      const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Não foi possível concluir a ação.");
      if (action === "submit") { setRoundId(""); setIssuePage(1); }
      setEditing(null); setFormRevision(value => value + 1); await load(); onChange?.(); setMessage("Operação concluída.");
    } catch (error) { setMessage((error as Error).message); await load().catch(() => undefined); }
    finally { setBusy(false); }
  }
  function issueSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); void mutate(editing ? "editIssue" : "issue", { ...Object.fromEntries(new FormData(event.currentTarget)), ...(editing ? { issueId: editing.id } : {}) }); }
  if (!data) return <p role="status">{message || "Carregando análise…"}</p>;
  const current = data.selectedId === data.latest?.id;
  const showWork = !correspondent || view === "work";
  const showHistory = !correspondent || view === "history";
  return <section className="space-y-4" aria-label="Workflow documental">
    {showWork && <div className={box}><h2 className="text-lg font-bold">{correspondent ? correspondentStatus(data.folder.status).title : `Análise documental · ${label(data.folder.status)}`}</h2>{correspondent ? <p className="text-sm text-slate-600">{data.canStart ? "Visualize os documentos e clique em Iniciar análise para registrar correções ou concluir." : data.canAnalyze ? "Confira os documentos, registre o que precisa ser corrigido e escolha sua conclusão." : data.folder.status === "PENDENCIA_DOCUMENTAL" ? "O responsável comercial está providenciando as correções. Quando reenviar, o cliente voltará para reanálise." : "Consulte os documentos e o histórico desta análise."} {data.openIssues} correções em aberto.</p> : <p>Rodada atual: {data.latest?.sequence ?? "Ainda não enviada"} · Total: {data.total} · Pendências abertas: {data.openIssues}</p>}<p>Responsável: {(data.folder.responsiblePerson ?? data.folder.broker)?.name ?? "Responsável legado"}</p>
      <div className="flex flex-wrap gap-2">{data.canSubmit && <button disabled={busy || data.openIssues > 0} className={button} onClick={() => { if (window.confirm(data.latest ? "Reenviar esta pasta e criar nova rodada?" : "Enviar esta pasta para análise?")) void mutate("submit"); }}>{data.latest ? "Reenviar para análise" : "Enviar para análise"}</button>}{data.canStart && <button disabled={busy} className={`${button} bg-blue-700 text-white`} onClick={() => void mutate("start")}>Iniciar análise</button>}<button disabled={busy} className={button} onClick={() => void load().catch(error => setMessage(error.message))}>Atualizar análise</button></div>
      {message && <p role="status" className="rounded bg-amber-50 p-3 text-sm">{message}</p>}
      <p className="text-sm text-gray-600">Você pode anexar novos documentos durante o trabalho. Os documentos recebidos e o histórico da análise são preservados.</p>
    </div>}
    {showWork && data.canAnalyze && <div className={box}><h3 className="font-semibold">Concluir a análise</h3><p className="text-sm text-slate-600">Para solicitar correções, registre pelo menos uma correção abaixo. Para reprovar ou aprovar com condições, informe o motivo ou as condições.</p><label className="block">Parecer / condições / motivo<textarea value={observation} maxLength={10000} className={control} rows={4} onChange={event => setObservation(event.target.value)} /></label><div className="flex flex-wrap gap-2"><button disabled={busy || !observation.trim()} className={button} onClick={() => void mutate("note", { observation })}>Salvar parecer</button>{[["PENDENCIA_DOCUMENTAL", "Solicitar correções"], ["APROVADO", "✓ Aprovar documentação"], ["CONDICIONADO", "Aprovar condicionado"], ["REPROVADO", "Reprovar"]].map(([result, title]) => <button key={result} disabled={busy || (result === "PENDENCIA_DOCUMENTAL" ? data.openIssues === 0 : data.openIssues > 0) || (["CONDICIONADO", "REPROVADO"].includes(result) && !observation.trim())} className={`${button} ${result === "APROVADO" ? "bg-emerald-700 text-white" : result === "REPROVADO" ? "bg-red-700 text-white" : result === "PENDENCIA_DOCUMENTAL" ? "border-amber-300 bg-amber-50 text-amber-950" : "bg-blue-50 text-blue-900"}`} onClick={() => { if (window.confirm(`Concluir a análise: ${title}?`)) void mutate("finish", { result, observation }); }}>{title}</button>)}</div></div>}
    {showWork && data.canAnalyze && <form id={`correction-${folderId}`} key={`${editing?.id ?? correction?.id ?? "new"}-${formRevision}`} className={box} onSubmit={issueSubmit}><h3 className="font-semibold">{editing ? "Revisar pendência" : "Solicitar correção de documento"}</h3><label className="block">Descrição<textarea name="message" className={control} required maxLength={3000} defaultValue={editing?.message ?? ""} /></label><div className="grid gap-3 sm:grid-cols-3">
      <label>Pessoa<select name="personId" className={control} defaultValue={editing?.personId ?? correction?.personId ?? ""}><option value="">Geral da pasta</option>{data.folder.people.map(person => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label>
      <label>Tipo documental<select name="documentTypeId" className={control} defaultValue={editing?.documentTypeId ?? correction?.documentTypeId ?? ""}><option value="">Sem tipo específico</option>{data.types.map(type => <option key={type.id} value={type.id}>{type.name}</option>)}</select></label>
      <label>Documento<select name="documentId" className={control} defaultValue={editing?.documentId ?? correction?.id ?? ""}><option value="">Sem documento específico</option>{correction && !data.documents.some(document => document.id === correction.id) && <option value={correction.id}>Documento selecionado na lista de documentos</option>}{data.documents.map(document => <option key={document.id} value={document.id}>{document.originalFileName}</option>)}</select></label>
    </div><p className="text-sm">Se vincular pessoa/tipo e documento, as referências precisam corresponder. A lista mostra até 100 documentos recebidos para a análise selecionada.</p><button disabled={busy} className={button}>Registrar correção</button>{editing && <button type="button" className={button} onClick={() => setEditing(null)}>Cancelar edição</button>}</form>}
    {showHistory && <div className={box}><h3 className="font-semibold">{correspondent ? "Análises anteriores" : "Rodadas e histórico"}</h3>{data.rounds.map(round => <article key={round.id} className="border-b pb-3 text-sm"><button className="underline font-semibold" onClick={() => { setRoundId(round.id); setIssuePage(1); setEditing(null); }}>{correspondent ? `Análise de ${date(round.sentAt)}` : `Rodada ${round.sequence}`} · {round.analysis ? correspondentStatus(round.analysis.result).title : "Em andamento"}</button><p>Enviada: {date(round.sentAt)} · Correspondente: {round.correspondent.name}</p>{round.events.map((event, index) => <p key={index}>{documentationEventLabels[event.eventType] ?? "Análise atualizada"} por {event.actor?.name ?? "Sistema"} · {date(event.createdAt)}</p>)}<p>Concluída: {date(round.closedAt)} · {round._count.documents} documentos recebidos · {round._count.pendingItems} pendências registradas</p>{round.analysis?.observation && <p className="whitespace-pre-wrap">Parecer: {round.analysis.observation}</p>}</article>)}{!data.total && <p>Nenhuma análise enviada ainda.</p>}<div className="flex flex-wrap items-center gap-3"><button className={button} disabled={page === 1 || busy} onClick={() => setPage(page - 1)}>Análises mais recentes</button><span>Página {page}</span><button className={button} disabled={page * 10 >= data.total || busy} onClick={() => setPage(page + 1)}>Análises anteriores</button><button className={button} onClick={() => { setRoundId(""); setIssuePage(1); }}>Análise atual</button></div></div>}
    {data.selectedId && <div className={box}><h3 className="font-semibold">Correções da análise {current ? "atual" : "selecionada"}</h3>{data.issues.map(issue => <article key={issue.id} className="space-y-1 border-b py-3 text-sm"><strong>{issue.status === "OPEN" ? "Aberta" : issue.status === "RESOLVED" ? "Resolvida" : "Cancelada"}</strong><p className="whitespace-pre-wrap">{issue.message}</p><p>{issue.person?.name ?? "Geral da pasta"} · {issue.documentType?.name ?? "Sem tipo"} · {issue.document?.originalFileName ?? "Sem documento"}</p><p>{issue.createdBy.name} · {date(issue.createdAt)}{issue.resolvedAt && ` · Resolvida por ${issue.resolvedBy?.name ?? "—"} em ${date(issue.resolvedAt)}`}</p>{current && issue.status === "OPEN" && <div className="flex gap-2">{data.canResolve && <button disabled={busy} className={button} onClick={() => void mutate("resolve", { issueId: issue.id })}>Marcar como resolvida</button>}{showWork && data.canAnalyze && <><button disabled={busy} className={button} onClick={() => setEditing(issue)}>Revisar</button><button disabled={busy} className={button} onClick={() => { if (window.confirm("Cancelar esta pendência preservando o histórico?")) void mutate("cancelIssue", { issueId: issue.id }); }}>Cancelar pendência</button></>}</div>}</article>)}{!data.issues.length && <p>Nenhuma correção solicitada nesta análise.</p>}<div className="flex flex-wrap items-center gap-3"><button className={button} disabled={issuePage === 1 || busy} onClick={() => setIssuePage(issuePage - 1)}>Pendências anteriores</button><span>Página {issuePage}</span><button className={button} disabled={issuePage * 20 >= data.issueTotal || busy} onClick={() => setIssuePage(issuePage + 1)}>Mais pendências</button></div></div>}
  </section>;
}
