"use client";
import {useEffect,useState,type FormEvent} from 'react';
import type {PerformanceReport} from '@/lib/marketing/performance.server';
import {change} from '@/lib/marketing/performance';
import {PerformanceChart,type ChartPoint} from './performance-chart';
import {BrokerEvolution} from './performance-broker';
type Options={accounts:{id:string;name:string;currency:string}[];brokers:{id:string;name:string}[]};
const field='rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm';
const money=(value:string|null,currency:string)=>value===null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency}).format(Number(value));
const weekdays=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
export function PerformanceScreen(){
 const [query,setQuery]=useState('period=month&compare=true&currency=BRL'),[revision,setRevision]=useState(0),[result,setResult]=useState<{key:string;data?:PerformanceReport;error?:string}>(),[options,setOptions]=useState<Options>();
 const [view,setView]=useState('Evolução'),[cumulative,setCumulative]=useState(false),[cost,setCost]=useState<'metaSpend'|'effectiveSpend'>('effectiveSpend');
 const key=`${query}:${revision}`,data=result?.key===key?result.data:undefined,error=result?.key===key?result.error:undefined;
 useEffect(()=>{const controller=new AbortController();fetch('/api/marketing/options',{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json();}).then(setOptions).catch(()=>{});return()=>controller.abort();},[]);
 useEffect(()=>{const controller=new AbortController();fetch(`/api/marketing/performance?${query}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error??'Consulta indisponível.');return body;}).then(data=>setResult({key,data})).catch(e=>{if(!controller.signal.aborted)setResult({key,error:e.message});});return()=>controller.abort();},[query,key]);
 function filter(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget),params=new URLSearchParams();for(const [k,v] of form)if(typeof v==='string'&&v)params.append(k,v);if(params.get('period')!=='custom'){params.delete('from');params.delete('to');}setQuery(params.toString());}
 const metricCost=cost==='effectiveSpend'?'cplEffective':'cplMeta';
 function points(series:PerformanceReport['current']['series']):ChartPoint[]{let complete=true;return series.map(d=>{complete=complete&&d.covered;const values=cumulative?d.cumulative:d;return {date:d.date,spend:values[cost],leads:values.leads,available:d.covered||d.rows>0,partial:cumulative?!complete:!d.covered};});}
 const current=data?.current,previous=data?.comparison;
 return <div className="space-y-5">
  <div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Desempenho</h2><button className={field} onClick={()=>setRevision(r=>r+1)}>Atualizar leitura</button></div>
  <p className="text-sm text-slate-600">Leads reportados pela Meta: conversas iniciadas em 7 dias. Não representam leads recebidos ou atendidos no CRM/Flyhub. Esta tela consulta os dados sincronizados; não chama a Meta.</p>
  <form onSubmit={filter} className="flex flex-wrap items-end gap-3 rounded-xl border bg-white p-4">
   <label className="grid gap-1 text-sm">Período<select name="period" defaultValue="month" className={field}><option value="week">Últimos 7 dias</option><option value="month">Mês até hoje</option><option value="previous">Mês anterior completo</option><option value="custom">Personalizado</option></select></label>
   <label className="grid gap-1 text-sm">De<input name="from" type="date" className={field}/></label><label className="grid gap-1 text-sm">Até<input name="to" type="date" className={field}/></label>
   <label className="grid gap-1 text-sm">Conta Meta<select name="accountId" className={field}><option value="">Todas as contas</option>{options?.accounts.map(a=><option key={a.id} value={a.id}>{a.name} ({a.currency})</option>)}</select></label>
   <label className="grid gap-1 text-sm">Moeda<select name="currency" className={field}><option>BRL</option>{[...new Set(options?.accounts.map(a=>a.currency))].filter(c=>c!=='BRL').map(c=><option key={c}>{c}</option>)}</select></label>
   <label className="grid gap-1 text-sm">Responsáveis (Ctrl para vários)<select name="personId" multiple className={`${field} h-24`}><option value="">Todos</option><option value="unassigned">Sem responsável</option>{options?.brokers.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>
   <label className="grid gap-1 text-sm">Comparação<select name="compare" className={field}><option value="true">Período anterior equivalente</option><option value="false">Desativada</option></select></label><button className="rounded-lg bg-teal-700 px-4 py-2 text-white">Aplicar filtros</button>
  </form>
  {error&&<p role="alert" className="rounded-lg bg-red-50 p-4 text-red-800">{error}</p>}{!data&&!error&&<p role="status">Carregando dados sincronizados…</p>}
  {data&&current&&<>
   <p className="text-sm">{data.range.from} a {data.range.to}{data.previous?` · Anterior: ${data.previous.from} a ${data.previous.to}`:''} · {data.timezone}. Moedas não são convertidas nem somadas entre si.</p>
   <details className="text-sm"><summary className="cursor-pointer">Contas e última sincronização</summary>{data.accounts.map(a=><p key={a.id}>{a.name} · {a.timezone} · {a.lastSyncedAt?new Date(a.lastSyncedAt).toLocaleString('pt-BR',{timeZone:a.timezone}):'Sem sincronização confirmada'}</p>)}{!data.accounts.length&&<p>Nenhuma conta disponível nesta moeda.</p>}</details>
   {(!current.complete||(previous&&!previous.complete))&&<p className="rounded-lg bg-amber-50 p-4 text-sm text-amber-900">Cobertura incompleta ou dia em andamento. Totais representam somente registros confirmados; ausência de sincronização não significa zero. Variações são provisórias. Meses com durações distintas são comparados pelas datas indicadas.</p>}
   {data.syncIssues.length>0&&<p className="text-sm text-amber-900">{data.syncIssues.length} execução(ões) pendente(s), em andamento ou com falha no intervalo. Confira Configurações.</p>}
   <div className="flex flex-wrap gap-3"><label className="text-sm">Investimento <select value={cost} onChange={e=>setCost(e.target.value as typeof cost)} className={field}><option value="effectiveSpend">Custo efetivo com regra histórica</option><option value="metaSpend">Gasto informado pela Meta</option></select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={cumulative} onChange={e=>setCumulative(e.target.checked)}/>Evolução acumulada</label></div>
   <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
    ['Investimento total',money(current.totals[cost],data.currency)],['Leads Meta',String(current.totals.leads)],['CPL',money(current.totals[metricCost],data.currency)],['Média diária de leads',current.totals.averageLeads.toFixed(2)],
    ...(previous?[['Variação investimento',`${change(current.totals[cost],previous.totals[cost]).percent??'—'}%`],['Variação leads',`${change(current.totals.leads,previous.totals.leads).percent??'—'}%`],['Variação CPL',`${change(current.totals[metricCost],previous.totals[metricCost]).percent??'—'}%`]]:[])
   ].map(([title,value])=><div key={title} className="rounded-xl border bg-white p-4"><p className="text-sm text-slate-500">{title}</p><strong className="text-xl">{value}</strong></div>)}</div>
   <p className="text-sm text-slate-600">Gasto Meta: {money(current.totals.metaSpend,data.currency)} · Custo efetivo: {money(current.totals.effectiveSpend,data.currency)}. O acréscimo é o já registrado ou corrigido por vigência; não reaplicamos 12,15%.</p>
   <nav aria-label="Visões de desempenho" className="flex flex-wrap gap-2">{['Evolução','Comparação de períodos','Dias e horários','Corretores'].map(v=><button key={v} aria-pressed={view===v} className={`${field} ${view===v?'bg-teal-50 font-semibold':''}`} onClick={()=>setView(v)}>{v}</button>)}</nav>
   {(view==='Evolução'||view==='Comparação de períodos')&&<PerformanceChart points={points(current.series)} previous={previous?points(previous.series):[]} currency={data.currency} label={cumulative?'Acumulado dos registros confirmados (pode estar incompleto)':'Investimento e leads por dia — registros confirmados'}/>}
   {view==='Evolução'&&<details><summary className="cursor-pointer font-medium">Dados diários e cobertura</summary><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Data','Gasto Meta','Custo efetivo','Leads','CPL','Cobertura'].map(t=><th key={t} className="p-3">{t}</th>)}</tr></thead><tbody>{current.series.map(d=><tr key={d.date} className="border-t"><td className="p-3">{d.date}</td><td>{money(d.metaSpend,data.currency)}</td><td>{money(d.effectiveSpend,data.currency)}</td><td>{d.leads}</td><td>{money(d[metricCost],data.currency)}</td><td>{d.covered?'Sincronizado':'Parcial / não sincronizado'}</td></tr>)}</tbody></table></div></details>}
   {view==='Comparação de períodos'&&(previous?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Indicador','Atual','Anterior','Diferença absoluta','Variação %'].map(t=><th className="p-3" key={t}>{t}</th>)}</tr></thead><tbody>{[{label:'Investimento',now:current.totals[cost],old:previous.totals[cost],monetary:true},{label:'Leads',now:current.totals.leads,old:previous.totals.leads,monetary:false},{label:'CPL',now:current.totals[metricCost],old:previous.totals[metricCost],monetary:true}].map(r=>{const delta=change(r.now,r.old);return <tr key={r.label} className="border-t"><td className="p-3">{r.label}</td><td>{r.monetary?money(r.now===null?null:String(r.now),data.currency):r.now}</td><td>{r.monetary?money(r.old===null?null:String(r.old),data.currency):r.old}</td><td>{r.monetary?money(delta.absolute,data.currency):delta.absolute??'—'}</td><td>{delta.percent===null?'Não calculável (base zero/ausente)':`${delta.percent}%`}</td></tr>;})}</tbody></table></div>:<p>Ative a comparação nos filtros.</p>)}
   {view==='Dias e horários'&&<><h3 className="font-semibold">Dias da semana — calendário local das contas</h3><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Dia','Investimento','Leads Meta','CPL','Média de leads por ocorrência'].map(t=><th className="p-3" key={t}>{t}</th>)}</tr></thead><tbody>{current.weekdays.map(d=><tr key={d.day} className="border-t"><td className="p-3">{weekdays[d.day]}</td><td>{money(d[cost],data.currency)}</td><td>{d.leads}</td><td>{money(d[metricCost],data.currency)}</td><td>{d.averageLeads.toFixed(2)}</td></tr>)}</tbody></table></div><aside className="rounded-xl border bg-slate-50 p-5"><h3 className="font-semibold">Faixas horárias: indisponíveis nesta versão</h3><p className="mt-2 text-sm">{data.hourly.reason}</p><p className="mt-2 text-sm">Um resultado agregado por hora pela Meta não informa o instante exato de chegada de uma conversa no WhatsApp.</p></aside></>}
   {view==='Corretores'&&<div className="space-y-3">{[...new Set([...current.brokers,...(previous?.brokers??[])].map(b=>b.id))].map(id=>{
    const broker=current.brokers.find(b=>b.id===id),old=previous?.brokers.find(b=>b.id===id);
    return <details key={id} className="rounded-xl border bg-white p-4"><summary className="cursor-pointer"><strong>{broker?.name??old?.name}</strong> · Investimento {money(broker?.[cost]??'0.00',data.currency)} · Leads {broker?.leads??0} · CPL {money(broker?.[metricCost]??null,data.currency)}{previous&&` · Δ investimento ${change(broker?.[cost]??'0.00',old?.[cost]??'0.00').percent??'—'}% · Δ leads ${change(broker?.leads??0,old?.leads??0).percent??'—'}% · Δ CPL ${change(broker?.[metricCost]??null,old?.[metricCost]??null).percent??'—'}%`}</summary>
     {broker&&<BrokerEvolution broker={broker} currency={data.currency} cost={cost} partial={!current.complete}/>}
     {old&&<details className="mt-4"><summary className="cursor-pointer">Evolução do período anterior</summary><BrokerEvolution broker={old} currency={data.currency} cost={cost} partial={!previous?.complete}/></details>}
    </details>;
   })}{!current.brokers.length&&<p>Nenhum registro confirmado para os filtros selecionados.</p>}<p className="text-sm text-slate-600">A responsabilidade é a vigente no dia do gasto, incluindo responsáveis históricos inativos. Semanas começam na segunda-feira. Use os filtros para selecionar um ou vários responsáveis.</p></div>}
  </>}
 </div>;
}
