"use client";
import { useEffect, useState, type FormEvent } from "react";
import type { officeFinance } from "@/lib/broker-office/finance.server";
import type { officeMarketing } from "@/lib/broker-office/marketing.server";
import type { officeDashboard } from "@/lib/broker-office/dashboard.server";
import { fundingNatures, recoveryMethods } from "@/lib/marketing/funding-policy";
type Json<T> = T extends Date ? string : T extends (infer U)[] ? Json<U>[] : T extends object ? { [K in keyof T]: Json<T[K]> } : T;
type Finance = Json<Awaited<ReturnType<typeof officeFinance>>>;
type Marketing = Json<Awaited<ReturnType<typeof officeMarketing>>>;
type Operation = Json<Awaited<ReturnType<typeof officeDashboard>>>;
type Dashboard = { operation: Operation; finance: Pick<Finance, "linked" | "position" | "period">; marketing: Pick<Marketing, "linked" | "totals" | "unavailable"> };
const labels: Record<string, string> = { ADVANCE: "Vale / adiantamento", DISCOUNT: "Desconto", BONUS: "Bonificação", REIMBURSEMENT: "Reembolso", OTHER: "Outro ajuste", CREDIT: "Crédito", DEBIT: "Débito", AVAILABLE: "Disponível para compensação", PARTIAL: "Parcial", APPLIED: "Compensado", CANCELLED: "Cancelado", OPEN: "Em aberto", PAID: "Pago", PENDING: "Pendente", SCHEDULED: "Agendado", ATO: "Ato / primeira etapa", BANCO: "Banco / segunda etapa", PREMIO: "Prêmio", COMPLEMENTO: "Complemento", PERSON: "Corretor", FLYIMOB: "Flyimob", CONFIRMED: "Confirmado", BROKER: "Corretor", MANAGER: "Gerente", INDICATOR: "Indicador" };
const label = (value: string) => labels[value] ?? value.replaceAll("_", " ");
const money = (value: string, currency = "BRL") => new Intl.NumberFormat("pt-BR", { style: "currency", currency }).format(Number(value));
const date = (value: string | null) => value ? new Intl.DateTimeFormat("pt-BR", { timeZone: "UTC" }).format(new Date(value)) : "Não informada";
const control = "w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-base";
function Card({ title, value, href, note }: { title: string; value: string | number; href?: string; note?: string }) {
  const content = <><p className="text-sm text-slate-600">{title}</p><p className="mt-2 text-2xl font-semibold tracking-tight text-slate-900 break-words">{value}</p>{note && <p className="mt-2 text-xs text-slate-500">{note}</p>}</>;
  return href ? <a href={href} className="rounded-2xl border bg-white p-4 hover:border-teal-600 focus:ring-2 focus:ring-teal-600">{content}</a> : <div className="rounded-2xl border bg-white p-4">{content}</div>;
}
function Receipts({ items }: { items: { name: string; href: string }[] }) { return <div className="flex flex-wrap gap-2">{items.map(r => <a key={r.href} className="text-sm text-teal-700 underline break-all" href={r.href}>{r.name}</a>)}</div>; }
function History({ rows }: { rows: { description: string; amount: string; date?: string }[] }) { return rows.length ? <details className="mt-3"><summary className="cursor-pointer text-sm text-teal-700">Histórico de movimentações ({rows.length})</summary><ul className="mt-2 space-y-2 text-sm">{rows.map((r, i) => <li key={i}>{r.date && `${date(r.date)} · `}{r.description} · {money(r.amount)}</li>)}</ul></details> : null; }
export default function Office({ section, initialQuery = "period=month" }: { section: "dashboard" | "marketing" | "finance"; initialQuery?: string }) {
  const [query, setQuery] = useState(initialQuery), [retry, setRetry] = useState(0), [from, setFrom] = useState(""), [to, setTo] = useState(""), [range, setRange] = useState<{ from: string; to: string }>();
  const [finance, setFinance] = useState<Finance>(), [marketing, setMarketing] = useState<Marketing>(), [dashboard, setDashboard] = useState<Dashboard>(), [error, setError] = useState(""), [busy, setBusy] = useState(true);
  useEffect(() => {
    const abort = new AbortController(); let active = true;
    fetch(`/api/broker-office/${section}?${query}`, { cache: "no-store", signal: abort.signal }).then(async r => { const result = await r.json(); if (!r.ok) throw Error(result.error); return result; }).then(result => { if (!active) return; setRange(result.range); setFrom(result.range.from); setTo(result.range.to); setError(""); if (section === "finance") setFinance(result.data); else if (section === "marketing") setMarketing(result.data); else setDashboard(result.data); }).catch(e => { if (active && e.name !== "AbortError") setError(e.message); }).finally(() => { if (active) setBusy(false); });
    return () => { active = false; abort.abort(); };
  }, [query, section, retry]);
  function choose(params: string) { setBusy(true); setFinance(undefined); setMarketing(undefined); setDashboard(undefined); setError(""); setQuery(params); setRetry(r => r + 1); window.history.replaceState(null, "", `${window.location.pathname}?${params}${window.location.hash}`); }
  function filter(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const values = new FormData(e.currentTarget); choose(new URLSearchParams({ period: "custom", from: String(values.get("from") ?? ""), to: String(values.get("to") ?? "") }).toString()); }
  const link = (path: string, hash = "") => `${path}?${query}${hash}`;
  return <div className="mx-auto max-w-6xl space-y-6 min-w-0">
    <header><p className="text-xs uppercase tracking-widest font-semibold text-teal-700">Meu escritório · Flyimob</p><h1 className="mt-2 text-3xl font-semibold">{section === "dashboard" ? "Seu negócio em um olhar" : section === "marketing" ? "Meu marketing" : "Meu financeiro"}</h1><p className="mt-2 text-sm text-slate-600">Dados da sua operação, atualizados a partir dos registros da Flyimob.</p></header>
    <nav aria-label="Meu escritório" className="flex flex-wrap gap-2">{[["/admin/corretor/dashboard", "Dashboard"], ["/admin/corretor/marketing", "Marketing"], ["/admin/corretor/financeiro", "Financeiro"]].map(([href, name]) => <a key={href} href={link(href)} className="rounded-xl border px-4 py-2 text-sm hover:bg-teal-50">{name}</a>)}</nav>
    <form onSubmit={filter} className="rounded-2xl border bg-slate-50 p-4 space-y-3"><div className="flex flex-wrap gap-2">{[["month", "Mês atual"], ["previous", "Mês anterior"], ["last30", "Últimos 30 dias"]].map(([preset, text]) => <button key={preset} type="button" className="rounded-lg border bg-white px-3 py-2 text-sm" disabled={busy} onClick={() => choose(`period=${preset}`)}>{text}</button>)}</div><div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><label className="text-sm">Data inicial<input className={control} type="date" name="from" required value={from} onChange={e => setFrom(e.target.value)} /></label><label className="text-sm">Data final<input className={control} type="date" name="to" required value={to} onChange={e => setTo(e.target.value)} /></label><button disabled={busy} className="rounded-xl bg-teal-700 px-4 py-2 text-white disabled:opacity-50">Consultar</button></div></form>
    {error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4">{error}<button className="ml-3 underline" onClick={() => { setBusy(true); setRetry(r => r + 1); }}>Tentar novamente</button></p>}
    {busy && <p role="status" aria-live="polite">Consultando sua operação…</p>}
    {!busy && !error && range && <p className="text-sm text-slate-500">Período: {date(range.from)} a {date(range.to)}. Os históricos seguem a data original de cada operação.</p>}
    {!busy && !error && dashboard && <>
      {!dashboard.finance.linked && <p className="rounded-xl border p-4">Sem participante financeiro vinculado ao seu login. Os indicadores financeiros não representam seu histórico até a administração revisar o vínculo existente.</p>}
      {dashboard.marketing.unavailable > 0 && <p className="rounded-xl bg-amber-50 p-4">Marketing com cobertura parcial: {dashboard.marketing.unavailable} observações indisponíveis. Consulte os detalhes antes de comparar períodos.</p>}
      <div className="grid gap-3 grid-cols-2 lg:grid-cols-4"><Card title="Clientes cadastrados no CRM" value={dashboard.operation.crm.reduce((s, r) => s + r.count, 0)} href="/admin/clientes" note="Cadastros no período; não equivale a leads entregues pela Meta." /><Card title="Documentos ativos coletados" value={dashboard.operation.documents} href="/documentacoes" /><Card title="Pastas em análise" value={dashboard.operation.folders.filter(r => ["EM_ANALISE", "EM_REANALISE", "AGUARDANDO_CORRESPONDENTE"].includes(r.status)).reduce((s, r) => s + r.count, 0)} href="/documentacoes" note="Situação atual das pastas criadas no período." /><Card title="Vendas com direito registrado" value={dashboard.finance.period.sales} href={link("/admin/corretor/financeiro", "#comissoes")} /></div>
      <div className="grid gap-3 grid-cols-2 lg:grid-cols-4"><Card title="Aprovações" value={dashboard.operation.folders.filter(r => r.status === "APROVADO").reduce((s, r) => s + r.count, 0)} href="/documentacoes" /><Card title="Aprovações condicionadas" value={dashboard.operation.folders.filter(r => r.status === "CONDICIONADO").reduce((s, r) => s + r.count, 0)} href="/documentacoes" /><Card title="Direitos gerados no período" value={money(dashboard.finance.period.generated)} href={link("/admin/corretor/financeiro", "#comissoes")} /><Card title="Pagamentos no período" value={money(dashboard.finance.period.payments)} href={link("/admin/corretor/financeiro", "#pagamentos")} note="Pagamentos efetivos; não inclui compensações de vales." /></div>
      <div className="grid gap-3 sm:grid-cols-2">{dashboard.marketing.totals.map(t => <Card key={t.currency} title="Consumo de marketing no período" value={money(t.effectiveSpend, t.currency)} href={link("/admin/corretor/marketing")} note={`${t.leads} leads reportados · CPL ${t.cpl ? money(t.cpl, t.currency) : "indisponível"}`} />)}<Card title="Previsto sem recebimento da empresa" value={money(dashboard.finance.position.projectedWithoutCompanyReceipt)} href={link("/admin/corretor/financeiro")} note="Projeção registrada; não é saldo disponível." /></div>
      {!dashboard.marketing.totals.length && <p>Sem resultados de campanhas confirmados no período. Nenhum resultado foi estimado.</p>}
    </>}
    {!busy && !error && marketing && <>
      {!marketing.linked && <p className="rounded-xl border p-4">Seu login ainda não tem vínculo com uma pessoa operacional. Campanhas vinculadas diretamente ao login podem aparecer; aportes e bonificações exigem vínculo explícito em Usuários / Equipe.</p>}
      {marketing.unavailable > 0 && <p className="rounded-xl bg-amber-50 p-4">Há {marketing.unavailable} observações indisponíveis. Os totais abaixo incluem somente métricas confirmadas.</p>}
      <div className="grid gap-3 sm:grid-cols-3">{marketing.totals.flatMap(t => [<Card key={`${t.currency}-spend`} title="Consumo atribuído" value={money(t.effectiveSpend, t.currency)} note={`Mídia na Meta: ${money(t.metaSpend, t.currency)}; custo operacional conforme regra existente.`} />, <Card key={`${t.currency}-leads`} title="Leads reportados pela Meta" value={t.leads} />, <Card key={`${t.currency}-cpl`} title="Custo por lead" value={t.cpl ? money(t.cpl, t.currency) : "Indisponível"} />])}</div>
      <section className="space-y-3"><h2 className="text-xl font-semibold">Recursos e posição de mídia</h2><p className="text-sm text-slate-600">Acumulado até o fim do período. Crédito de anúncios e financiamento não são dinheiro pago ao corretor. A posição econômica não é o saldo físico da conta compartilhada na Meta.</p>{marketing.positions.map(p => <div key={p.currency} className="grid gap-3 grid-cols-2 lg:grid-cols-4"><Card title="Aportes próprios no período" value={money(p.periodContributions, p.currency)} href="#recursos" /><Card title="Bonificações no período" value={money(p.periodBonuses, p.currency)} href="#recursos" /><Card title="Recursos recebidos no período" value={money(p.periodFundingReceived, p.currency)} href="#recursos" /><Card title="Financiamento em aberto" value={money(p.outstandingDebt, p.currency)} href="#recursos" /><Card title="Posição econômica de mídia" value={money(p.mediaPosition, p.currency)} note={p.missing ? "Histórico incompleto; não tratar como saldo disponível." : "Posição registrada; não comprova saldo disponível na Meta."} /></div>)}</section>
      <section className="space-y-3"><h2 className="text-xl font-semibold">Campanhas da sua operação</h2>{!marketing.campaigns.length && <p>Sem campanhas vinculadas no período.</p>}{marketing.campaigns.map(c => <article key={c.id} className="rounded-2xl border p-4"><h3 className="font-semibold break-words">{c.name}</h3>{c.results.length ? c.results.map(r => <p key={r.currency} className="mt-2 text-sm">{money(r.effectiveSpend, r.currency)} · {r.leads} leads · CPL {r.cpl ? money(r.cpl, r.currency) : "indisponível"}</p>) : <p className="text-sm text-slate-500">Sem métricas confirmadas atribuídas a você neste período.</p>}</article>)}</section>
      <section className="space-y-3"><h2 className="text-xl font-semibold">Evolução diária</h2>{marketing.evolution.map(e => <details key={e.currency} className="rounded-xl border p-4"><summary>{e.currency} · {e.complete ? "Período coberto pela importação" : "Cobertura parcial; consulte os dias"}</summary><div className="mt-3 space-y-2">{e.series.map(d => <p key={d.date} className="text-sm">{date(d.date)} · {money(d.effectiveSpend, e.currency)} · {d.leads} leads {d.covered ? "" : "· cobertura não confirmada"}</p>)}</div></details>)}</section>
      <ResourceHistory data={marketing} />
    </>}
    {!busy && !error && finance && <>
      {!finance.linked && <p className="rounded-xl border p-4">Não há participante financeiro explicitamente vinculado ao seu login ou pessoa. A administração deve revisar o vínculo existente; nenhum histórico foi associado por nome ou e-mail.</p>}
      <p className="text-sm text-slate-600">Posição atual de todos os registros: valores pagos, direitos pendentes e ajustes separados. O filtro de período afeta o histórico abaixo. A previsão da etapa é de recebimento pela empresa, não uma promessa de pagamento ao corretor.</p>
      <div className="grid gap-3 grid-cols-2 lg:grid-cols-4"><Card title="Direitos registrados" value={money(finance.position.generated)} href="#comissoes" /><Card title="Direitos pagos por alocação" value={money(finance.position.commissionPaid)} href="#comissoes" /><Card title="Pendente com recebimento da empresa" value={money(finance.position.pendingWithCompanyReceipt)} href="#comissoes" /><Card title="Projetado sem recebimento da empresa" value={money(finance.position.projectedWithoutCompanyReceipt)} href="#comissoes" /><Card title="Vales a compensar" value={money(finance.position.advancesOpen)} href="#ajustes" /><Card title="Descontos a compensar" value={money(finance.position.discountsOpen)} href="#ajustes" /><Card title="Outros débitos a compensar" value={money(finance.position.otherDebitsOpen)} href="#ajustes" /><Card title="Créditos a compensar" value={money(finance.position.creditsOpen)} href="#ajustes" /></div>
      <section id="comissoes" className="space-y-3"><h2 className="text-xl font-semibold">Comissões e direitos por venda</h2>{!finance.entitlements.length && <p>Sem direitos registrados neste período.</p>}{finance.entitlements.map(e => <article key={e.id} className="rounded-2xl border p-4"><h3 className="font-semibold">{e.client} · {label(e.stage)}</h3><p className="mt-1 text-sm">{date(e.date)} · {label(e.role)} · {e.cancelled ? "Cancelado" : label(e.status)}</p><div className="mt-3 grid gap-2 sm:grid-cols-3 text-sm"><p>Direito: <strong>{money(e.amount)}</strong></p><p>Pago: {money(e.paid)}</p><p>A liquidar: {money(e.remaining)}</p></div><p className="mt-2 text-sm">Previsão da etapa: {date(e.expectedAt)} · {e.receivedByCompany ? "Existe recebimento confirmado pela empresa" : "Sem recebimento confirmado pela empresa"}</p><History rows={e.history} /></article>)}</section>
      <section id="ajustes" className="space-y-3"><h2 className="text-xl font-semibold">Vales, descontos e créditos</h2><p className="text-sm text-slate-600">Um vale pode ser compensado em várias vendas. Original e compensações aparecem no mesmo registro; não são novos pagamentos.</p>{!finance.adjustments.length && <p>Sem ajustes no período.</p>}{finance.adjustments.map(a => <article key={a.id} className="rounded-2xl border p-4"><h3 className="font-semibold">{label(a.type)} · {money(a.amount)}</h3><p className="text-sm mt-2">{date(a.date)} · {label(a.effect)} · {label(a.status)} · Restante {money(a.remaining)}</p>{a.description && <p className="mt-2">{a.description}</p>}<History rows={a.history} /><Receipts items={a.receipts} /></article>)}</section>
      <section id="pagamentos" className="space-y-3"><h2 className="text-xl font-semibold">Pagamentos e comprovantes</h2>{!finance.payments.length && <p>Sem pagamentos no período.</p>}{finance.payments.map(p => <article key={p.id} className="rounded-2xl border p-4"><h3 className="font-semibold">{money(p.amount)} · {label(p.status)}</h3><p className="text-sm mt-2">{date(p.date)}</p><History rows={p.history} /><Receipts items={p.receipts} /></article>)}</section>
      <FinanceMarketing query={query} />
    </>}
  </div>;
}
function ResourceHistory({ data }: { data: Marketing }) { return <section id="recursos" className="space-y-3"><h2 className="text-xl font-semibold">Histórico de recursos de marketing</h2><p className="text-sm text-slate-600">Estes registros também aparecem no Financeiro como referência de mídia. Não são somados aos pagamentos ou comissões.</p>{!data.history.length && <p>Sem movimentações vinculadas no período.</p>}{data.history.map(m => <article key={m.id} className="rounded-2xl border p-4"><h3 className="font-semibold">{fundingNatures[m.nature as keyof typeof fundingNatures] ?? (m.kind === "CONTRIBUTION" ? "Aporte" : "Ajuste de mídia")} · {money(m.amount, m.currency)}</h3><p className="mt-2 text-sm">{date(m.date)} · {label(m.status)} · Origem: {label(m.origin)}</p>{m.recoveryMethod && <p className="text-sm">{recoveryMethods[m.recoveryMethod as keyof typeof recoveryMethods]}</p>}{m.reason && <p className="mt-2">{m.reason}</p>}{m.description && <p className="mt-2">{m.description}</p>}<Receipts items={m.receipts} /></article>)}</section>; }
function FinanceMarketing({ query }: { query: string }) {
  const [result, setResult] = useState<{ query: string; data?: Marketing; error?: string }>();
  useEffect(() => { const abort = new AbortController(); let active = true; fetch(`/api/broker-office/marketing?${query}`, { cache: "no-store", signal: abort.signal }).then(async r => { const d = await r.json(); if (!r.ok) throw Error(d.error); return d.data; }).then(data => { if (active) setResult({ query, data }); }).catch(e => { if (active && e.name !== "AbortError") setResult({ query, error: e.message }); }); return () => { active = false; abort.abort(); }; }, [query]);
  const current = result?.query === query ? result : undefined;
  return current?.data ? <ResourceHistory data={current.data} /> : <p className="text-sm">{current?.error ? `Recursos de marketing indisponíveis: ${current.error}` : "Consultando os registros de mídia relacionados…"}</p>;
}
