import { requestContext } from "../documentacoes/request-context";
import assert from "node:assert/strict";
import { test } from "node:test";
import { scheduledMarketingPass, startMarketingScheduler } from "../../src/lib/marketing/scheduled.server";
import { Prisma } from "@prisma/client";
import { prisma } from "../../src/lib/prisma";
import { economicLedger, physicalReconciliation, coveredDays, localDayBoundary, movementMoney } from "../../src/lib/marketing/finance-calculations";
import { parseAvailableBalance, balanceObservation, syncAccountBalance } from "../../src/lib/marketing/balances.server";
import { createMoneyMovement, transitionMoneyMovement, createReconciliationMark } from "../../src/lib/marketing/finance.server";
import { marketingFinanceOptions, moneyMovementList, marketingLung } from "../../src/lib/marketing/finance-queries.server";
import { MetaClient } from "../../src/lib/marketing/meta.server";
import { authorize, day, type MarketingViewer } from "../../src/lib/marketing/policy";
import { downloadMoneyReceipt, uploadMoneyReceipt } from "../../src/lib/marketing/finance-receipts.server";
import { POST } from "../../src/app/api/marketing/finance/movements/route";
import { createSessionToken } from "../../src/lib/auth.server";
import { readFileSync } from "node:fs";
const D=(value:string)=>new Prisma.Decimal(value);
const viewer:MarketingViewer={user:{id:"owner",tenantId:"tenant",role:"OWNER"},tenant:{id:"tenant",isPlatform:false}};
const date=day("2026-09-01");
const input={accountId:"account",personId:"person",kind:"CONTRIBUTION",origin:"PERSON",status:"CONFIRMED",effectiveDate:"2026-09-01",amount:"400.00",currency:"BRL",idempotencyKey:"request"};
type Args={where:Record<string,unknown>;data:Record<string,unknown>};
function fake(overrides:Record<string,unknown>={}){
 const events:Record<string,unknown>[]=[],movements:Record<string,unknown>[]=[];
 const tx={metaAdAccount:{findFirst:async({where}:Args)=>where.tenantId==="tenant"&&where.id==="account"?{id:"account",currency:"BRL",timezone:"America/Sao_Paulo"}:null},operationPerson:{findFirst:async()=>({id:"person",active:true,mergedIntoId:null,operationalRole:"DIRECTOR",user:null})},marketingMoneyMovement:{findUnique:async()=>null,create:async({data}:Args)=>{movements.push(data);return {id:"movement"};},findFirst:async()=>({id:"movement",version:0,status:"PENDING"}),updateMany:async()=>({count:1})},marketingReconciliationMark:{findUnique:async()=>null,create:async({data}:Args)=>{movements.push(data);return {id:"mark"};}},marketingAuditEvent:{create:async({data}:Args)=>{events.push(data);return data;}},...overrides};
 const db={...tx,$transaction:async(fn:(tx:unknown)=>unknown)=>{const old=events.length,m=movements.length;try{return await fn(tx);}catch(e){events.length=old;movements.length=m;throw e;}}} as unknown as typeof prisma;
 return {db,events,movements};
}
const m=(amount="400.00",status="CONFIRMED")=>({amount:D(amount),status,kind:"CONTRIBUTION",origin:"PERSON",personId:"person",currency:"BRL",effectiveDate:date});
const metric=(value="483.20")=>({date,currency:"BRL",state:"CONFIRMED",metaSpend:D("400"),effectiveSpend:D(value),leads:10,campaign:{id:"campaign",assignments:[{personId:"person",validFrom:date,validTo:null as Date|null}]}});
for(const [value,position] of [["399.99","0.01"],["400.00","0.00"],["483.20","-83.20"]])test(`economic position ${position} uses effective spend`,()=>{const row=economicLedger([m()],[metric(value)],date,date)[0];assert.equal(row.position,position);assert.equal(row.operationalCredit,position.startsWith("-")?"83.20":"0.00");});
test("pending and cancelled contributions never provide credit",()=>{assert.equal(economicLedger([m("400","PENDING"),m("400","CANCELLED")],[metric()],date,date)[0].position,"-483.20");});
test("history belongs to the responsible person at each day's half-open validity",()=>{const a=metric("10");a.campaign.assignments=[{personId:"person",validFrom:date,validTo:day("2026-09-02") as Date|null},{personId:"next",validFrom:day("2026-09-02"),validTo:null} as typeof a.campaign.assignments[number]];const b={...a,date:day("2026-09-02")};const rows=economicLedger([], [a,b],date,b.date);assert.equal(rows.find(r=>r.id==="person")?.consumption,"10.00");assert.equal(rows.find(r=>r.id==="next")?.consumption,"10.00");});
test("historical contribution uses effective date and positions accumulate before report period",()=>{const rows=economicLedger([m()],[{...metric("100"),date:day("2026-09-02")}],day("2026-09-02"),day("2026-09-02"));assert.equal(rows[0].position,"300.00");assert.equal(rows[0].periodContributions,"0.00");});
test("currencies never mix and merged identity resolves without mutating movements",()=>{const a=m();const rows=economicLedger([a,{...m("5"),currency:"USD"}],[],date,date,id=>id==="person"?"canonical":id);assert.equal(rows.length,2);assert.equal(a.personId,"person");assert.equal(rows[0].id,"canonical");});
test("physical reconciliation uses Meta spend without economic markup",()=>{const exact=physicalReconciliation(D("0"),[m()],[metric("483.20")],date,date,D("0"),D("0.02"));assert.equal(exact.expected,"0.00");assert.equal(exact.matched,true);const diff=physicalReconciliation(D("100"),[m()],[metric()],date,date,D("103"),D("0.02"));assert.equal(diff.expected,"100.00");assert.equal(diff.difference,"3.00");assert.equal(diff.matched,false);});
test("internal compensation does not invent physical Meta cash",()=>{const adjustment={...m("25"),kind:"ADJUSTMENT",affectsPhysicalBalance:false};assert.equal(economicLedger([adjustment],[],date,date)[0].position,"25.00");assert.equal(physicalReconciliation(D("0"),[adjustment],[],date,date,D("0"),D("0.02")).matched,true);});
for(const [display,currency,expected] of [["Saldo disponível (R$689,39 BRL)","BRL","689.39"],["Saldo disponível (R$1.890,70 BRL)","BRL","1890.70"],["Saldo disponível (R$0,00 BRL)","BRL","0.00"],["Available funds ($1,234.56 USD)","USD","1234.56"],["Saldo disponível (€123,45 EUR)","EUR","123.45"]])test(`physical parsing ${currency} ${expected}`,()=>{assert.equal(parseAvailableBalance(display,currency)?.toFixed(2),expected);});
for(const [display,currency] of [["Visa ****1234","BRL"],["Saldo disponível (R$10,00 USD)","BRL"],["Saldo disponível (R$1,234 BRL)","BRL"],["Saldo disponível (R$1.23,45 BRL)","BRL"],["Saldo disponível (R$-10,00 BRL)","BRL"],["Available funds (¥123 JPY)","JPY"]])test(`unsupported balance ${display}`,()=>assert.equal(parseAvailableBalance(display,currency),null));
test("funding field absence does not fall back to balance and sanitized payload excludes tokens",()=>{const a=balanceObservation({id:"act_1",currency:"BRL",balance:"99999",access_token:"forbidden"},"BRL","1");assert.equal(a.availableBalance,null);assert.equal(a.state,"UNSUPPORTED");assert.equal(JSON.stringify(a.payload).includes("forbidden"),false);assert.throws(()=>balanceObservation({id:"act_2",currency:"BRL"},"BRL","1"));});
test("coverage merges full ranges, rejects missing day and local boundaries respect account timezone",()=>{assert.equal(coveredDays([{periodFrom:date,periodTo:date},{periodFrom:day("2026-09-02"),periodTo:day("2026-09-03")}],date,day("2026-09-03")),true);assert.equal(coveredDays([{periodFrom:date,periodTo:date}],date,day("2026-09-03")),false);assert.equal(localDayBoundary("2026-09-01","America/Sao_Paulo").toISOString(),"2026-09-01T03:00:00.000Z");});
test("amount validator rejects floating garbage, excess precision, zero, Infinity and negative deposits",()=>{for(const value of [1,"1e3","0","NaN","Infinity","0.001","-1"])assert.throws(()=>movementMoney(value));assert.equal(movementMoney("-1.01",true).toFixed(2),"-1.01");});
test("historical person without login can contribute without role mutation",async()=>{const f=fake();await createMoneyMovement(viewer,input,f.db);assert.equal(f.movements[0].personId,"person");assert.deepEqual(f.movements[0].effectiveDate,date);assert.equal(f.movements[0].createdById,"owner");assert.equal(f.events[0].eventType,"MARKETING_MONEY_CREATED");});
test("Flyimob contribution and pending adjustment have explicit economic origins",async()=>{const f=fake();await createMoneyMovement(viewer,{...input,origin:"FLYIMOB",personId:null},f.db);await createMoneyMovement(viewer,{...input,kind:"ADJUSTMENT",amount:"-10",adjustmentType:"CORRECTION",reason:"Correção sintética",affectsPhysicalBalance:false,status:"PENDING"},f.db);assert.equal(f.movements[0].personId,null);assert.equal(f.movements[1].status,"PENDING");});
test("inactive person rejects new contribution but historical ledger still includes identity",async()=>{const f=fake({operationPerson:{findFirst:async()=>({active:false,mergedIntoId:null,operationalRole:"BROKER"})}});await assert.rejects(createMoneyMovement(viewer,input,f.db));assert.equal(economicLedger([m()],[],date,date)[0].id,"person");});
test("tenant and currency mismatches are rejected",async()=>{const f=fake();await assert.rejects(createMoneyMovement(viewer,{...input,accountId:"foreign"},f.db));await assert.rejects(createMoneyMovement(viewer,{...input,currency:"USD"},f.db));assert.equal(f.movements.length,0);});
test("OWNER controls money; DIRECTOR can read only; authentication is separate from operational hierarchy",async()=>{const director={...viewer,user:{...viewer.user,role:"DIRECTOR" as const}};authorize(director);for(const fn of [()=>createMoneyMovement(director,input,fake().db),()=>transitionMoneyMovement(director,"movement",{status:"CANCELLED",version:0,reason:"x"},fake().db),()=>createReconciliationMark(director,{},fake().db)])await assert.rejects(fn);assert.throws(()=>authorize({...viewer,tenant:{id:"foreign",isPlatform:false}}));});
test("cancellation has reason and before/after audit; payload fields cannot be edited",async()=>{const f=fake();await transitionMoneyMovement(viewer,"movement",{version:0,status:"CANCELLED",reason:"Aporte duplicado"},f.db);assert.deepEqual(f.events[0].metadata,{before:{status:"PENDING",version:0},after:{status:"CANCELLED",version:1,reason:"Aporte duplicado"}});await assert.rejects(transitionMoneyMovement(viewer,"movement",{version:0,status:"CANCELLED",reason:"x",amount:"50"},f.db));await assert.rejects(transitionMoneyMovement(viewer,"movement",{version:1,status:"CANCELLED",reason:"x"},f.db));});
test("creation audit failure rolls back deposit",async()=>{const f=fake({marketingAuditEvent:{create:async()=>{throw new Error("audit");}}});await assert.rejects(createMoneyMovement(viewer,input,f.db),/audit/);assert.equal(f.movements.length,0);});
test("same request key returns original without additional contribution",async()=>{const f=fake({marketingMoneyMovement:{findUnique:async()=>({...input,createdById:"owner",effectiveDate:date,amount:D(input.amount),note:null,reason:null,adjustmentType:null,affectsPhysicalBalance:true,id:"same"})}});assert.deepEqual(await createMoneyMovement(viewer,input,f.db),{id:"same"});assert.equal(f.events.length,0);});
for(const openingBalance of ["0","100.00"])test(`mark opening ${openingBalance} has immutable audit and timezone`,async()=>{const f=fake();await createReconciliationMark(viewer,{accountId:"account",effectiveDate:"2026-09-01",openingBalance,note:"Known synthetic balance",idempotencyKey:"mark"},f.db);assert.equal((f.movements[0].openingBalance as Prisma.Decimal).toFixed(2),D(openingBalance).toFixed(2));assert.equal((f.movements[0].effectiveAt as Date).toISOString(),"2026-09-01T03:00:00.000Z");});
test("balance snapshots are idempotent and inactive Meta account read is GET only",async()=>{let requests=0,saved:Record<string,unknown>|undefined;
 const f=fake({marketingBalanceSnapshot:{findUnique:async()=>saved?{state:"AVAILABLE"}:null,upsert:async({create}:{create:Record<string,unknown>})=>{saved=create;}},metaAdAccount:{findFirst:async()=>({externalId:"1",currency:"BRL",status:"PAUSED"})},metaConnectionAccount:{findFirst:async()=>({id:"link"})}});
 const client=new MetaClient("synthetic","secret",(async(url,init)=>{requests++;assert.equal(init?.method,"GET");assert.match(String(url),/act_1/);return Response.json({id:"act_1",currency:"BRL",funding_source_details:{display_string:"Saldo disponível (R$689,39 BRL)",id:"123",type:20}});}) as typeof fetch);
 await syncAccountBalance("tenant","account","connection","same",f.db,{client,credentialVersion:1});await syncAccountBalance("tenant","account","connection","same",f.db,{client,credentialVersion:1});assert.equal(requests,1);assert.equal((saved?.availableBalance as Prisma.Decimal).toFixed(2),"689.39");
});
test("snapshot timeout remains unavailable without throwing away history",async()=>{let state="";const f=fake({marketingBalanceSnapshot:{findUnique:async()=>null,upsert:async({create}:{create:{state:string}})=>{state=create.state;}},metaAdAccount:{findFirst:async()=>({externalId:"1",currency:"BRL"})},metaConnectionAccount:{findFirst:async()=>({id:"link"})}});const client=new MetaClient("synthetic","secret",(async()=>{throw new Error("network");}) as typeof fetch);assert.equal((await syncAccountBalance("tenant","account","connection","attempt",f.db,{client,credentialVersion:1})).state,"UNAVAILABLE");assert.equal(state,"UNAVAILABLE");});
test("receipt download and upload check tenant/access before storage",async()=>{let calls=0;const storage={ready:async()=>{},put:async()=>{calls++;},get:async()=>{calls++;return {bytes:new Uint8Array()};}};const f=fake({marketingMoneyReceipt:{findFirst:async()=>null}});await assert.rejects(downloadMoneyReceipt(viewer,"foreign",f.db,storage));await assert.rejects(uploadMoneyReceipt({...viewer,user:{...viewer.user,role:"DIRECTOR"}},"movement",new Request("https://flyimob.test"),f.db,storage));assert.equal(calls,0);});
test("finance read projections are tenant scoped and receipt keys are not projected",async()=>{const f=fake({marketingMoneyMovement:{findMany:async({where,select}:{where:{tenantId:string};select:Record<string,unknown>})=>{assert.equal(where.tenantId,"tenant");assert.equal(select.idempotencyKey,undefined);return [];},count:async()=>0}});assert.equal((await moneyMovementList(viewer,new URLSearchParams("tenantId=foreign"),f.db)).total,0);});
test("shared eligibility used for new financial people options",async()=>{const f=fake({metaAdAccount:{findMany:async()=>[]},operationPerson:{findMany:async()=>[{id:"p",name:"No login",operationalRole:"MANAGER",active:true,mergedIntoId:null},{id:"inactive",name:"Historical",operationalRole:"BROKER",active:false,mergedIntoId:null}]}});const o=await marketingFinanceOptions(viewer,f.db);assert.equal(o.people[0].eligible,true);assert.equal(o.people[1].eligible,false);});
test("money endpoint rejects anonymous caller before parsing body",async()=>{assert.equal((await requestContext(undefined,()=>POST(new Request("https://flyimob.test/api/marketing/finance/movements",{method:"POST",body:"not-json"})))).status,401);});
test("money endpoint denies DIRECTOR and rejects cross-site OWNER request",async t=>{process.env.SESSION_SECRET="synthetic-finance-secret";const delegate=prisma.user as unknown as {findFirst:unknown};const old=delegate.findFirst;let role="DIRECTOR";delegate.findFirst=async()=>({id:"owner",tenantId:"tenant",role,isActive:true,sessionVersion:0,name:"Synthetic",email:"synthetic@example.test",tenant:{id:"tenant",isPlatform:false,name:"Synthetic",slug:"synthetic",parentId:null}});t.after(()=>{delegate.findFirst=old;});const token=(role:"OWNER"|"DIRECTOR")=>createSessionToken({uid:"owner",tid:"tenant",role,sv:0});assert.equal((await requestContext(token("DIRECTOR"),()=>POST(new Request("https://flyimob.test/api/marketing/finance/movements",{method:"POST",body:"{}"})))).status,403);role="OWNER";assert.equal((await requestContext(token("OWNER"),()=>POST(new Request("https://flyimob.test/api/marketing/finance/movements",{method:"POST",headers:{origin:"https://foreign.test","sec-fetch-site":"cross-site"},body:"{}"})))).status,403);});
test("incremental migration does not alter prior metrics, rules or generic Financeiro",()=>{const sql=readFileSync("prisma/migrations/20261005160000_marketing_finance/migration.sql","utf8");assert.doesNotMatch(sql,/DROP TABLE|UPDATE "MarketingDailyMetric"|ALTER TABLE "Financial|UPDATE "CampaignBrokerAssignment"/);assert.match(sql,/DEFERRABLE INITIALLY DEFERRED/);assert.match(sql,/marketing_money_preserve/);});

function lungFixture(intraday=false) {
 const observedAt=new Date("2026-10-05T12:00:00Z");
 return fake({
  metaAdAccount:{findMany:async()=>[{id:"account",name:"Synthetic",currency:"BRL",timezone:"America/Sao_Paulo",status:"ACTIVE",sourceAccountStatus:1,lastSyncedAt:observedAt}]},
  marketingMoneyMovement:{count:async()=>1,findMany:async()=>[{...m("200"),accountId:"account",id:"deposit"}]},
  marketingDailyMetric:{count:async()=>1,findMany:async()=>[{...metric("12"),metaSpend:D("10"),sourceObservedAt:date,campaign:{id:"campaign",accountId:"account",name:"Synthetic",purpose:"CLIENTES",assignments:[{personId:"person",brokerId:null,validFrom:date,validTo:null,person:{name:"Historical director"},broker:null}]}}]},
  operationPerson:{findMany:async()=>[{id:"person",name:"Historical director",operationalRole:"DIRECTOR",active:false,mergedIntoId:null}]},
  marketingCampaign:{findMany:async()=>[{id:"campaign",accountId:"account",sourceStatus:"ACTIVE",effectiveStatus:"ACTIVE",assignments:[{personId:"person",brokerId:null,validFrom:date,validTo:null,broker:null}]}]},
  marketingReconciliationMark:{findMany:async()=>[{accountId:"account",effectiveDate:date,effectiveAt:new Date(intraday?"2026-09-01T12:00:00Z":"2026-09-01T03:00:00Z"),openingBalance:D("0"),tolerance:D("0.02"),note:"Known zero"}]},
  marketingBalanceSnapshot:{findFirst:async()=>({accountId:"account",observedAt,currency:"BRL",state:"AVAILABLE",availableBalance:D("190"),safeErrorCode:null,displayString:"Saldo disponível (R$190,00 BRL)"})},
  marketingAuditEvent:{findMany:async()=>[]},
  marketingSyncRun:{findMany:async()=>[{periodFrom:date,periodTo:day("2026-10-05"),finishedAt:observedAt}]},
 });
}
test("Pulmão keeps cumulative historical person position separate from physical reconciliation",async()=>{const report=await marketingLung(viewer,new URLSearchParams("period=custom&from=2026-09-01&to=2026-09-01"),lungFixture().db,new Date("2026-10-05T13:00:00Z"));assert.equal(report.table[0].position,"188.00");assert.equal(report.table[0].active,false);assert.equal(report.accounts[0].reconciliation?.status,"CONCILIADO");assert.equal(report.accounts[0].reconciliation?.expected,"190.00");assert.equal(report.totals[0].availableBalance,"190.00");});
test("intraday zero marker is preserved but cannot claim exact daily reconciliation",async()=>{const report=await marketingLung(viewer,new URLSearchParams(),lungFixture(true).db,new Date("2026-10-05T13:00:00Z"));assert.equal(report.accounts[0].reconciliation?.expected,null);assert.match(report.accounts[0].reconciliation!.status,/INTRADIÁRIO/);});
test("snapshot staleness and missing sync coverage suppress autonomy and exact reconciliation",async()=>{const f=lungFixture();const delegate=f.db.marketingSyncRun as unknown as {findMany:unknown};delegate.findMany=async()=>[];const report=await marketingLung(viewer,new URLSearchParams(),f.db,new Date("2026-10-05T13:00:00Z"));assert.equal(report.accounts[0].autonomyDays,null);assert.equal(report.accounts[0].dailyMetaSpend,null);assert.match(report.accounts[0].reconciliation!.status,/NECESSÁRIA/);});

test("scheduled pass creates one daily queue key and repeated hourly pass does not duplicate it",async()=>{
 let queued:Record<string,unknown>|null=null,created=0;
 const f=fake({metaAdAccount:{findMany:async()=>[{id:"account",tenantId:"tenant",timezone:"America/Sao_Paulo",status:"ACTIVE",sourceAccountStatus:1,lastSyncedAt:null,connections:[{connectionId:"connection"}]}]},
  marketingSyncRun:{findFirst:async()=>null,findUnique:async()=>queued,create:async({data}:Args)=>{created++;queued={id:"run",...data};return queued;},findMany:async()=>[],count:async()=>1},
  metaConnectionAccount:{findUnique:async()=>({selected:true,accessible:true,connection:{status:"AUTHORIZED",credentialCiphertext:Buffer.from([1]),expiresAt:null},account:{status:"ACTIVE"}})},
  marketingBalanceSnapshot:{findUnique:async()=>({state:"AVAILABLE"})}});
 await scheduledMarketingPass(f.db,new Date("2026-10-05T12:00:00Z"));await scheduledMarketingPass(f.db,new Date("2026-10-05T13:00:00Z"));assert.equal(created,1);assert.equal((queued as unknown as Record<string,unknown>).idempotencyKey,"scheduled:2026-10-05");
});
test("scheduler is never started by build, test or development processes",()=>{startMarketingScheduler();assert.equal((globalThis as typeof globalThis&{marketingScheduler?:unknown}).marketingScheduler,undefined);});
test("currency labels with conflicting symbols cannot invent available balance",()=>assert.equal(parseAvailableBalance("Available funds (R$123.45 USD)","USD"),null));

test("credential-version or account-selection change fences out a pending balance observation",async()=>{
 let stored=false;
 const f=fake({marketingBalanceSnapshot:{findUnique:async()=>null,upsert:async()=>{stored=true;}},metaAdAccount:{findFirst:async()=>({externalId:"1",currency:"BRL"})},metaConnectionAccount:{findFirst:async()=>null}});
 const client=new MetaClient("synthetic","secret",(async()=>Response.json({id:"act_1",currency:"BRL",funding_source_details:{display_string:"Saldo disponível (R$10,00 BRL)"}})) as typeof fetch);
 assert.equal((await syncAccountBalance("tenant","account","connection","changed",f.db,{client,credentialVersion:3})).state,"UNAVAILABLE");assert.equal(stored,false);
});
test("physical snapshot refreshes inactive account status without touching campaign history",async()=>{
 let status:number|undefined;
 const f=fake({marketingBalanceSnapshot:{findUnique:async()=>null,findFirst:async()=>null,upsert:async()=>{}},metaAdAccount:{findFirst:async()=>({externalId:"1",currency:"BRL"}),updateMany:async({data}:Args)=>{status=Number(data.sourceAccountStatus);}},metaConnectionAccount:{findFirst:async()=>({id:"link"})}});
 const client=new MetaClient("synthetic","secret",(async()=>Response.json({id:"act_1",currency:"BRL",account_status:2,funding_source_details:{display_string:"Saldo disponível (R$10,00 BRL)"}})) as typeof fetch);
 assert.equal((await syncAccountBalance("tenant","account","connection","status",f.db,{client,credentialVersion:3})).state,"AVAILABLE");assert.equal(status,2);
});

test("unsupported funding does not present an invented zero in aggregate Meta cash",async()=>{const f=lungFixture();Object.assign(f.db.marketingBalanceSnapshot,{findFirst:async()=>({accountId:"account",observedAt:new Date("2026-10-05T12:00:00Z"),state:"UNSUPPORTED",currency:"BRL",availableBalance:null,displayString:null,safeErrorCode:null})});const report=await marketingLung(viewer,new URLSearchParams(),f.db,new Date("2026-10-05T13:00:00Z"));assert.equal(report.totals[0].availableBalance,null);assert.equal(report.totals[0].autonomyDays,null);assert.equal(report.accounts[0].reconciliation?.status,"SALDO INDISPONÍVEL");});
