"use client";
import { useEffect, useState } from "react";
import { trainingFetch } from "./Training";
type Broker = { id: string; name: string; trainingAccess: { courseIds: string[]; syncPending: boolean; syncedAt: string | null } | null };
export default function AccessManager() {
  const [brokers, setBrokers] = useState<Broker[]>([]), [ids, setIds] = useState<string[]>([]), [selected, setSelected] = useState(""), [courses, setCourses] = useState<string[]>([]), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const load = async () => { const d = await trainingFetch("/api/admin/training/access"); setBrokers(d.brokers); setIds(d.courseIds); };
  useEffect(() => { let active = true; trainingFetch("/api/admin/training/access").then(d => { if (active) { setBrokers(d.brokers); setIds(d.courseIds); } }).catch(e => { if (active) setMessage(e.message); }); return () => { active = false; }; }, []);
  async function save() { setBusy(true); try { const d = await trainingFetch("/api/admin/training/access", "PUT", { brokerId: selected, courseIds: courses }); setMessage(d.syncPending ? "Permissões locais salvas. Sincronização pendente; tente sincronizar novamente quando a Horizonte estiver disponível." : "Permissões salvas e sincronizadas."); await load(); } catch (e) { setMessage((e as Error).message); } finally { setBusy(false); } }
  return <div className="space-y-4 max-w-3xl"><h1 className="text-2xl font-semibold">Acesso aos treinamentos</h1><p>Referências de cursos configuradas pelo operador. O contrato atual da Horizonte não oferece catálogo administrativo ao parceiro.</p>{message && <p role="status" className="border rounded p-3">{message}</p>}<label className="block">Corretor<select className="block border rounded p-3 w-full" value={selected} onChange={e => { setSelected(e.target.value); setCourses(brokers.find(b => b.id === e.target.value)?.trainingAccess?.courseIds ?? []); }}><option value="">Selecione</option>{brokers.map(b => <option key={b.id} value={b.id}>{b.name} {b.trainingAccess?.syncPending ? "— pendente" : ""}</option>)}</select></label>{!ids.length && <p>Configure HORIZONTE_COURSE_IDS com os IDs reais aprovados no escopo do cliente Horizonte.</p>}<fieldset disabled={busy || !selected} className="space-y-2"><legend>Cursos permitidos</legend>{Array.from(new Set([...ids, ...courses])).map(id => <label key={id} className="flex items-center gap-3 border rounded p-3 break-all"><input type="checkbox" checked={courses.includes(id)} onChange={e => setCourses(old => e.target.checked ? [...old, id] : old.filter(c => c !== id))} />{id}</label>)}<button className="border rounded p-3" onClick={save} disabled={busy || !selected}>{busy ? "Salvando…" : "Salvar / sincronizar"}</button><button className="border rounded p-3 ml-2" onClick={() => setCourses([])}>Desmarcar todos</button></fieldset><p className="text-sm">Desmarcar e salvar revoga o acesso. A Flyimob bloqueia imediatamente novas operações; uma URL de vídeo já emitida pode continuar válida até expirar.</p></div>;
}
